import { useState } from 'react'
import PatternsView from './PatternsView'
import StaffView from './StaffView'
import PlatformsView from './PlatformsView'
import TechStackView from './TechStackView'
import RightsView from './RightsView'

const ROLE_KEYS = [
  { key: 'cameramen',               label: 'Cameramen' },
  { key: 'onsiteAudio',             label: 'Onsite Audio' },
  { key: 'onsiteProductionManager', label: 'Onsite Production Manager' },
  { key: 'director',                label: 'Director' },
  { key: 'producer',                label: 'Producer' },
  { key: 'commentator',             label: 'Commentator' },
  { key: 'evsOperator',             label: 'EVS Operator' },
  { key: 'graphicsOperator',        label: 'Graphics Operator' },
  { key: 'mamCheckers',             label: 'MAM Checkers' },
]

const CAP_KEYS = ['cam2', 'cam4', 'cam8plus', 'studio', 'tennis', 'rugby']

function buildSnapshot() {
  const staff    = JSON.parse(localStorage.getItem('admin_staff')          || '{}')
  const profiles = JSON.parse(localStorage.getItem('admin_staff_profiles') || '{}')
  const date     = new Date().toISOString().slice(0, 10)

  const lines = []
  lines.push(`// Sports Calendar — Staff Seed Data`)
  lines.push(`// Generated by the Snapshot button in Admin.`)
  lines.push(`// To update: press Snapshot, replace this file with the downloaded seedStaff.js, then commit.`)
  lines.push(`// Applied on first load only when localStorage has no staff data.`)
  lines.push(`// Last snapshot: ${date}`)
  lines.push(``)
  lines.push(`export const SEED_STAFF = {`)

  for (const { key } of ROLE_KEYS) {
    const names = staff[key] || []
    lines.push(`  ${key}: [${names.map(n => `'${n.replace(/'/g, "\\'")}'`).join(', ')}],`)
  }

  lines.push(`}`)
  lines.push(``)
  lines.push(`export const SEED_STAFF_PROFILES = {`)

  for (const { key } of ROLE_KEYS) {
    const names = staff[key] || []
    if (!names.length) continue

    lines.push(`  ${key}: {`)
    for (const name of names) {
      const p       = profiles[key]?.[name] || {}
      const caps    = p.caps || {}
      const capStr  = CAP_KEYS.map(c => `${c}: ${caps[c] ? 'true' : 'false'}`).join(', ')
      const isStaff   = p.isStaff !== false ? 'true' : 'false'
      const email     = (p.email || '').replace(/'/g, "\\'")
      const seniority = p.seniority || 1
      lines.push(`    '${name.replace(/'/g, "\\'")}': { isStaff: ${isStaff}, email: '${email}', seniority: ${seniority}, caps: { ${capStr} } },`)
    }
    lines.push(`  },`)
  }

  lines.push(`}`)
  return lines.join('\n')
}

function downloadText(filename, content) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function AdminView({ snapshotUnlocked, allEvents, onNavigate, onActivateComps }) {
  const [adminTab, setAdminTab] = useState('patterns')

  function handleSnapshot() {
    downloadText('seedStaff.js', buildSnapshot())
  }

  function handleTamsAll() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const tams = platforms.find(p => p.name?.toLowerCase() === 'tams')
    if (!tams) { alert('No platform named "TAMS" found. Add it in Admin → Platforms first.'); return }

    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    for (const event of allEvents) {
      if (!decisions[event.id]) decisions[event.id] = {}
      decisions[event.id][tams.id] = 'Y'
    }
    localStorage.setItem('editorial_decisions', JSON.stringify(decisions))
    alert(`TAMS set to Y for all ${allEvents.length} events.`)
  }

  function handleClearTams() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const tams = platforms.find(p => p.name?.toLowerCase() === 'tams')
    if (!tams) { alert('No platform named "TAMS" found. Add it in Admin → Platforms first.'); return }

    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    for (const event of allEvents) {
      if (decisions[event.id]) decisions[event.id][tams.id] = ''
    }
    localStorage.setItem('editorial_decisions', JSON.stringify(decisions))
    alert(`TAMS cleared for all ${allEvents.length} events.`)
  }

  function handleSelectMany() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const findPlatform = name => platforms.find(p => p.name?.toLowerCase() === name.toLowerCase())
    const skyMcr = findPlatform('Sky MCR')
    const tams = findPlatform('TAMS')
    const itvEaling = findPlatform('ITV Ealing')
    const bbc1 = findPlatform('BBC 1')

    const missing = [
      !skyMcr && 'Sky MCR',
      !tams && 'TAMS',
      !itvEaling && 'ITV Ealing',
      !bbc1 && 'BBC 1',
    ].filter(Boolean)
    if (missing.length) {
      alert(`Missing platform(s): ${missing.join(', ')}. Add them in Admin → Platforms first.`)
      return
    }

    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    const setDecision = (eventId, platformId, value) => {
      if (!decisions[eventId]) decisions[eventId] = {}
      decisions[eventId][platformId] = value
    }
    const eventsFor = competitionId => allEvents.filter(e => e.extendedProps?.competitionId === competitionId)
    const sample = (events, fraction) => events.filter(() => Math.random() < fraction)

    for (const event of eventsFor('championship_2627')) {
      setDecision(event.id, skyMcr.id, 'Y')
      setDecision(event.id, tams.id, 'Y')
    }
    for (const event of sample(eventsFor('league_one_2627'), 0.5)) {
      setDecision(event.id, skyMcr.id, 'Y')
    }
    for (const event of sample(eventsFor('league_two_2627'), 0.25)) {
      setDecision(event.id, skyMcr.id, 'Y')
    }
    for (const event of sample(eventsFor('atp_tour'), 0.5)) {
      setDecision(event.id, itvEaling.id, 'Y')
    }
    for (const event of eventsFor('atp_tour')) {
      setDecision(event.id, bbc1.id, 'Y')
    }
    for (const event of eventsFor('scottish_premiership')) {
      setDecision(event.id, bbc1.id, 'Y')
    }

    localStorage.setItem('editorial_decisions', JSON.stringify(decisions))
    onActivateComps?.(['championship_2627', 'league_one_2627', 'league_two_2627', 'atp_tour', 'scottish_premiership'])
    onNavigate?.('editorial')
  }

  function handleClearMany() {
    localStorage.setItem('editorial_decisions', '{}')
    alert('All editorial decisions cleared for every platform.')
  }

  return (
    <div className="admin-view">
      <div className="admin-content">
        {adminTab === 'patterns'   && <PatternsView />}
        {adminTab === 'staff'      && <StaffView allEvents={allEvents} />}
        {adminTab === 'platforms'  && <PlatformsView />}
        {adminTab === 'techstack'  && <TechStackView />}
        {adminTab === 'rights'     && <RightsView />}
      </div>
      <div className="admin-bottom-bar">
        <button className={`admin-tab-btn${adminTab === 'patterns'  ? ' active' : ''}`} onClick={() => setAdminTab('patterns')}>Patterns</button>
        <button className={`admin-tab-btn${adminTab === 'staff'     ? ' active' : ''}`} onClick={() => setAdminTab('staff')}>Staff</button>
        <button className={`admin-tab-btn${adminTab === 'platforms' ? ' active' : ''}`} onClick={() => setAdminTab('platforms')}>Platforms</button>
        <button className={`admin-tab-btn${adminTab === 'techstack' ? ' active' : ''}`} onClick={() => setAdminTab('techstack')}>Tech Stack</button>
        <button className={`admin-tab-btn${adminTab === 'rights'    ? ' active' : ''}`} onClick={() => setAdminTab('rights')}>Rights</button>
        <div className="admin-snapshot-group">
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleSnapshot}
          >
            Snapshot
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleTamsAll}
          >
            TAMS All
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleClearTams}
          >
            Clear TAMS
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleSelectMany}
          >
            Select Many Events
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleClearMany}
          >
            Clear Many Events
          </button>
        </div>
      </div>
    </div>
  )
}

export default AdminView
