import { useState } from 'react'
import PatternsView from './PatternsView'
import StaffView from './StaffView'
import PlatformsView from './PlatformsView'
import TechStackView from './TechStackView'
import RightsView from './RightsView'
import BookableAssetsView from './BookableAssetsView'
import { saveToStorage } from '../services/storage'

const ROLE_KEYS = [
  { key: 'cameramen',               label: 'Cameramen' },
  { key: 'onsiteAudio',             label: 'Onsite Audio' },
  { key: 'onsiteProductionManager', label: 'Onsite Production Manager' },
  { key: 'director',                label: 'Director' },
  { key: 'producer',                label: 'Producer' },
  { key: 'commentator',             label: 'Commentator' },
  { key: 'evsOperator',             label: 'EVS Operator' },
  { key: 'graphicsOperator',        label: 'Graphics Operator' },
  { key: 'mamCheckers',             label: 'MAM Checkers' },
]

const CAP_KEYS = ['cam2', 'cam4', 'cam8plus', 'studio', 'tennis', 'rugby']

function buildSnapshot() {
  const staff    = JSON.parse(localStorage.getItem('admin_staff')          || '{}')
  const profiles = JSON.parse(localStorage.getItem('admin_staff_profiles') || '{}')
  const date     = new Date().toISOString().slice(0, 10)

  const lines = []
  lines.push(`// Sports Calendar — Staff Seed Data`)
  lines.push(`// Generated by the Snapshot button in Admin.`)
  lines.push(`// To update: press Snapshot, replace this file with the downloaded seedStaff.js, then commit.`)
  lines.push(`// Applied on first load only when localStorage has no staff data.`)
  lines.push(`// Last snapshot: ${date}`)
  lines.push(``)
  lines.push(`export const SEED_STAFF = {`)

  for (const { key } of ROLE_KEYS) {
    const names = staff[key] || []
    lines.push(`  ${key}: [${names.map(n => `'${n.replace(/'/g, "\\'")}'`).join(', ')}],`)
  }

  lines.push(`}`)
  lines.push(``)
  lines.push(`export const SEED_STAFF_PROFILES = {`)

  for (const { key } of ROLE_KEYS) {
    const names = staff[key] || []
    if (!names.length) continue

    lines.push(`  ${key}: {`)
    for (const name of names) {
      const p       = profiles[key]?.[name] || {}
      const caps    = p.caps || {}
      const capStr  = CAP_KEYS.map(c => `${c}: ${caps[c] ? 'true' : 'false'}`).join(', ')
      const isStaff   = p.isStaff !== false ? 'true' : 'false'
      const email     = (p.email || '').replace(/'/g, "\\'")
      const seniority = p.seniority || 1
      lines.push(`    '${name.replace(/'/g, "\\'")}': { isStaff: ${isStaff}, email: '${email}', seniority: ${seniority}, caps: { ${capStr} } },`)
    }
    lines.push(`  },`)
  }

  lines.push(`}`)
  return lines.join('\n')
}

function buildRightsSnapshot() {
  const rights = JSON.parse(localStorage.getItem('rights_matrix') || '{}')
  const date   = new Date().toISOString().slice(0, 10)

  const lines = []
  lines.push(`// Sports Calendar — Rights Seed Data`)
  lines.push(`// Generated by the Snapshot Rights button in Admin.`)
  lines.push(`// To update: press Snapshot Rights, replace this file with the downloaded seedRights.js, then commit.`)
  lines.push(`// Applied on first load only when localStorage has no rights data.`)
  lines.push(`// Last snapshot: ${date}`)
  lines.push(``)
  lines.push(`export const SEED_RIGHTS_MATRIX = ${JSON.stringify(rights, null, 2)}`)
  return lines.join('\n')
}

function buildPatternsSnapshot() {
  const patterns = JSON.parse(localStorage.getItem('admin_patterns') || '[]')
  const date     = new Date().toISOString().slice(0, 10)

  const lines = []
  lines.push(`// Sports Calendar — Patterns Seed Data`)
  lines.push(`// Generated by the Snapshot Patterns button in Admin.`)
  lines.push(`// To update: press Snapshot Patterns, replace this file with the downloaded seedPatterns.js, then commit.`)
  lines.push(`// Applied on first load only when localStorage has no patterns data.`)
  lines.push(`// Last snapshot: ${date}`)
  lines.push(``)
  lines.push(`export const SEED_PATTERNS = ${JSON.stringify(patterns, null, 2)}`)
  return lines.join('\n')
}

function buildAssetsSnapshot() {
  const assets   = JSON.parse(localStorage.getItem('bookable_assets') || '[]')
  const bookings = JSON.parse(localStorage.getItem('asset_bookings')  || '[]')
  const date     = new Date().toISOString().slice(0, 10)

  const lines = []
  lines.push(`// Sports Calendar — Bookable Assets Seed Data`)
  lines.push(`// Generated by the Snapshot Assets button in Admin.`)
  lines.push(`// To update: press Snapshot Assets, replace this file with the downloaded seedBookableAssets.js, then commit.`)
  lines.push(`// Applied on first load only when localStorage has no bookable assets data.`)
  lines.push(`// Last snapshot: ${date}`)
  lines.push(``)
  lines.push(`export const SEED_BOOKABLE_ASSETS = ${JSON.stringify(assets, null, 2)}`)
  lines.push(``)
  lines.push(`export const SEED_ASSET_BOOKINGS = ${JSON.stringify(bookings, null, 2)}`)
  return lines.join('\n')
}

function downloadText(filename, content) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function AdminView({ snapshotUnlocked, allEvents, onNavigate, onActivateComps }) {
  const [adminTab, setAdminTab] = useState('patterns')

  function handleSnapshot() {
    downloadText('seedStaff.js', buildSnapshot())
  }

  function handleSnapshotPatterns() {
    downloadText('seedPatterns.js', buildPatternsSnapshot())
  }

  function handleSnapshotRights() {
    downloadText('seedRights.js', buildRightsSnapshot())
  }

  function handleSnapshotAssets() {
    downloadText('seedBookableAssets.js', buildAssetsSnapshot())
  }

  function handleInitAll() {
    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    for (const event of allEvents) {
      if (!decisions[event.id]) decisions[event.id] = {}
      decisions[event.id].initProduction = true
    }
    if (!saveToStorage('editorial_decisions', decisions)) return
    alert(`Init Production set for all ${allEvents.length} events.`)
  }

  function handleInitSelected() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const platformIds = platforms.map(p => p.id)
    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')

    let selectedCount = 0
    for (const event of allEvents) {
      const eventDecisions = decisions[event.id] || {}
      const hasSelection = platformIds.some(id => eventDecisions[id] === 'Y' || eventDecisions[id] === 'P')
      if (!decisions[event.id]) decisions[event.id] = {}
      decisions[event.id].initProduction = hasSelection
      if (hasSelection) selectedCount++
    }
    if (!saveToStorage('editorial_decisions', decisions)) return
    alert(`Init Production cleared, then set for ${selectedCount} event(s) selected on at least one platform.`)
  }

  function handleClearAllInit() {
    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    for (const event of allEvents) {
      if (decisions[event.id]) decisions[event.id].initProduction = false
    }
    if (!saveToStorage('editorial_decisions', decisions)) return
    alert(`Init Production cleared for all ${allEvents.length} events.`)
  }

  function handleTamsAll() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const tams = platforms.find(p => p.name?.toLowerCase() === 'tams')
    if (!tams) { alert('No platform named "TAMS" found. Add it in Admin → Platforms first.'); return }

    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    for (const event of allEvents) {
      if (!decisions[event.id]) decisions[event.id] = {}
      decisions[event.id][tams.id] = 'Y'
    }
    if (!saveToStorage('editorial_decisions', decisions)) return
    alert(`TAMS set to Y for all ${allEvents.length} events.`)
  }

  function handleTamsSelected() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const tams = platforms.find(p => p.name?.toLowerCase() === 'tams')
    if (!tams) { alert('No platform named "TAMS" found. Add it in Admin → Platforms first.'); return }

    const otherPlatformIds = platforms.filter(p => p.id !== tams.id).map(p => p.id)
    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')

    let definiteCount = 0
    let possibleCount = 0
    for (const event of allEvents) {
      const eventDecisions = decisions[event.id] || {}
      const values = otherPlatformIds.map(id => eventDecisions[id])
      const isDefinite = values.includes('Y')
      const isPossible = !isDefinite && values.includes('P')
      if (!decisions[event.id]) decisions[event.id] = {}
      decisions[event.id][tams.id] = isDefinite ? 'Y' : isPossible ? 'P' : ''
      if (isDefinite) definiteCount++
      if (isPossible) possibleCount++
    }
    if (!saveToStorage('editorial_decisions', decisions)) return
    alert(`TAMS cleared, then set to Y for ${definiteCount} definite event(s) and P for ${possibleCount} possible-only event(s).`)
  }

  function handleClearTams() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const tams = platforms.find(p => p.name?.toLowerCase() === 'tams')
    if (!tams) { alert('No platform named "TAMS" found. Add it in Admin → Platforms first.'); return }

    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    for (const event of allEvents) {
      if (decisions[event.id]) decisions[event.id][tams.id] = ''
    }
    if (!saveToStorage('editorial_decisions', decisions)) return
    alert(`TAMS cleared for all ${allEvents.length} events.`)
  }

  function handleSelectMany() {
    const platforms = JSON.parse(localStorage.getItem('admin_platforms') || '[]')
    const findPlatform = name => platforms.find(p => p.name?.toLowerCase() === name.toLowerCase())
    const skyMcr = findPlatform('Sky MCR')
    const tams = findPlatform('TAMS')
    const itvEaling = findPlatform('ITV Ealing')
    const bbc1 = findPlatform('BBC 1')

    const missing = [
      !skyMcr && 'Sky MCR',
      !tams && 'TAMS',
      !itvEaling && 'ITV Ealing',
      !bbc1 && 'BBC 1',
    ].filter(Boolean)
    if (missing.length) {
      alert(`Missing platform(s): ${missing.join(', ')}. Add them in Admin → Platforms first.`)
      return
    }

    const decisions = JSON.parse(localStorage.getItem('editorial_decisions') || '{}')
    const setDecision = (eventId, platformId, value) => {
      if (!decisions[eventId]) decisions[eventId] = {}
      decisions[eventId][platformId] = value
    }
    const eventsFor = competitionId => allEvents.filter(e => e.extendedProps?.competitionId === competitionId)
    const sample = (events, fraction) => events.filter(() => Math.random() < fraction)

    for (const event of eventsFor('championship_2627')) {
      setDecision(event.id, skyMcr.id, 'Y')
      setDecision(event.id, tams.id, 'Y')
    }
    for (const event of sample(eventsFor('league_one_2627'), 0.5)) {
      setDecision(event.id, skyMcr.id, 'Y')
    }
    for (const event of sample(eventsFor('league_two_2627'), 0.25)) {
      setDecision(event.id, skyMcr.id, 'Y')
    }
    for (const event of sample(eventsFor('atp_tour'), 0.5)) {
      setDecision(event.id, itvEaling.id, 'Y')
    }
    for (const event of eventsFor('atp_tour')) {
      setDecision(event.id, bbc1.id, 'Y')
    }
    for (const event of eventsFor('scottish_premiership')) {
      setDecision(event.id, bbc1.id, 'Y')
    }

    if (!saveToStorage('editorial_decisions', decisions)) return
    onActivateComps?.(['championship_2627', 'league_one_2627', 'league_two_2627', 'atp_tour', 'scottish_premiership'])
    onNavigate?.('editorial')
  }

  function handleClearMany() {
    if (!saveToStorage('editorial_decisions', {})) return
    alert('All editorial decisions cleared for every platform.')
  }

  return (
    <div className="admin-view">
      <div className="admin-content">
        {adminTab === 'patterns'   && <PatternsView />}
        {adminTab === 'staff'      && <StaffView allEvents={allEvents} />}
        {adminTab === 'platforms'  && <PlatformsView />}
        {adminTab === 'techstack'  && <TechStackView />}
        {adminTab === 'rights'     && <RightsView />}
        {adminTab === 'bookableAssets' && <BookableAssetsView />}
      </div>
      <div className="admin-bottom-bar">
        <button className={`admin-tab-btn${adminTab === 'patterns'  ? ' active' : ''}`} onClick={() => setAdminTab('patterns')}>Patterns</button>
        <button className={`admin-tab-btn${adminTab === 'staff'     ? ' active' : ''}`} onClick={() => setAdminTab('staff')}>Staff</button>
        <button className={`admin-tab-btn${adminTab === 'platforms' ? ' active' : ''}`} onClick={() => setAdminTab('platforms')}>Platforms</button>
        <button className={`admin-tab-btn${adminTab === 'techstack' ? ' active' : ''}`} onClick={() => setAdminTab('techstack')}>Tech Stack</button>
        <button className={`admin-tab-btn${adminTab === 'rights'    ? ' active' : ''}`} onClick={() => setAdminTab('rights')}>Rights</button>
        <button className={`admin-tab-btn${adminTab === 'bookableAssets' ? ' active' : ''}`} onClick={() => setAdminTab('bookableAssets')}>Bookable Assets</button>
        <div className="admin-snapshot-group">
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleSnapshot}
          >
            Snapshot
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleSnapshotPatterns}
          >
            Snapshot Patterns
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleSnapshotRights}
          >
            Snapshot Rights
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleSnapshotAssets}
          >
            Snapshot Assets
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleTamsAll}
          >
            TAMS All
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleTamsSelected}
          >
            TAMS selected
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleClearTams}
          >
            Clear TAMS
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleInitAll}
          >
            Init All
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleInitSelected}
          >
            Init selected
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleClearAllInit}
          >
            Clear All Init
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleSelectMany}
          >
            Select Many Events
          </button>
          <button
            className={`admin-tab-btn admin-snapshot-btn${snapshotUnlocked ? ' visible' : ''}`}
            disabled={!snapshotUnlocked}
            tabIndex={snapshotUnlocked ? 0 : -1}
            onClick={handleClearMany}
          >
            Clear Many Events
          </button>
        </div>
      </div>
    </div>
  )
}

export default AdminView
