// Sports Calendar — Rights Seed Data
// Generated by the Snapshot Rights button in Admin.
// To update: press Snapshot Rights, replace this file with the downloaded seedRights.js, then commit.
// Applied on first load only when localStorage has no rights data.
// Last snapshot: 2026-08-24

export const SEED_RIGHTS_MATRIX = {
  "premier_league": {
    "plat_seed_1": "Y",
    "plat_seed_2": "Y",
    "plat_seed_4": "Y",
    "plat_seed_5": "N",
    "plat_seed_6": "N",
    "plat_1787574724991_q49j1": "Y"
  },
  "championship": {
    "plat_seed_2": "Y",
    "plat_seed_6": "Y"
  },
  "league_one": {
    "plat_seed_1": "Y",
    "plat_seed_3": "Y",
    "plat_seed_6": "Y",
    "plat_1787574724991_q49j1": "Y"
  },
  "league_two": {
    "plat_seed_4": "",
    "plat_seed_3": "Y",
    "plat_seed_1": "N",
    "plat_seed_2": "N",
    "plat_seed_6": "Y",
    "plat_1787574724991_q49j1": "N"
  },
  "gallagher_premiership": {
    "plat_seed_4": "",
    "plat_seed_2": "N",
    "plat_seed_1": "N",
    "plat_seed_6": "Y",
    "plat_1787574724991_q49j1": "N"
  },
  "atp_tour": {
    "plat_seed_2": "Y",
    "plat_seed_3": "Y",
    "plat_seed_5": "N",
    "plat_seed_6": "Y"
  },
  "wta_tour": {
    "plat_seed_6": "Y",
    "plat_seed_1": "N",
    "plat_seed_2": "Y",
    "plat_seed_3": "Y",
    "plat_1787574724991_q49j1": "N"
  },
  "scottish_premiership": {
    "plat_seed_3": "Y",
    "plat_seed_6": "Y"
  },
  "championship_2627": {
    "plat_seed_3": "Y",
    "plat_seed_6": "Y"
  },
  "league_one_2627": {
    "plat_seed_3": "Y",
    "plat_seed_1": "Y",
    "plat_seed_6": "Y",
    "plat_1787574724991_q49j1": "Y"
  },
  "league_two_2627": {
    "plat_seed_3": "Y",
    "plat_seed_1": "N",
    "plat_seed_2": "N",
    "plat_seed_6": "Y",
    "plat_1787574724991_q49j1": "N"
  },
  "rugby_world_cup_2027": {
    "plat_seed_3": "Y",
    "plat_seed_1": "Y",
    "plat_seed_6": "Y",
    "plat_1787574724991_q49j1": "Y"
  },
  "nfl_2026": {
    "plat_seed_3": "Y",
    "plat_seed_1": "N",
    "plat_seed_2": "Y",
    "plat_seed_6": "Y",
    "plat_1787574724991_q49j1": "N"
  }
}